name: homes
version: '${project.version}'
main: br.com.sicro.homes.Main
commands:
  sethome:
    description: "Salvar homes."
  home:
    description: "Ir para homes."
  delhome:
    description: "Remover homes."
  homes:
    description: "Mostra a lista de homes."
